/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './signup.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './signup.component';
const styles_SignupComponent:any[] = [i0.styles];
export const RenderType_SignupComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SignupComponent,data:{}});
export function View_SignupComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  signup works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_SignupComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-signup',
      ([] as any[]),(null as any),(null as any),(null as any),View_SignupComponent_0,
      RenderType_SignupComponent)),i1.ɵdid(1,114688,(null as any),0,i2.SignupComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SignupComponentNgFactory:i1.ComponentFactory<i2.SignupComponent> = i1.ɵccf('app-signup',
    i2.SignupComponent,View_SignupComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovTUFUS1VML1dFQi9TTVQ0L3BlbXJvZ3JhbWFuLXdlYi1sYW5qdXQvR2VyYWxkby1USTJCL0pvYnNoZWV0IDEyL0dlcmFsZG8tVEkyQi9hdXRoLWRlbW8tc3RhcnRlci9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9NQVRLVUwvV0VCL1NNVDQvcGVtcm9ncmFtYW4td2ViLWxhbmp1dC9HZXJhbGRvLVRJMkIvSm9ic2hlZXQgMTIvR2VyYWxkby1USTJCL2F1dGgtZGVtby1zdGFydGVyL2F1dGgtZGVtby9zcmMvYXBwL3NpZ251cC9zaWdudXAuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovTUFUS1VML1dFQi9TTVQ0L3BlbXJvZ3JhbWFuLXdlYi1sYW5qdXQvR2VyYWxkby1USTJCL0pvYnNoZWV0IDEyL0dlcmFsZG8tVEkyQi9hdXRoLWRlbW8tc3RhcnRlci9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovTUFUS1VML1dFQi9TTVQ0L3BlbXJvZ3JhbWFuLXdlYi1sYW5qdXQvR2VyYWxkby1USTJCL0pvYnNoZWV0IDEyL0dlcmFsZG8tVEkyQi9hdXRoLWRlbW8tc3RhcnRlci9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC50cy5TaWdudXBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cbiAgc2lnbnVwIHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1zaWdudXA+PC9hcHAtc2lnbnVwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFHO2FBQUEsNENBRUM7TUFBQTs7O29CQ0ZKO01BQUE7Z0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
